### ISSUE TITLE
npm run dev failing

### ISSUE THREAD

**Issue by mroberts1** [noreading/bootstrap5-webpack-boilerplate#237]
I am getting the error below after installing and running the dev server. The server appears to start successfully, but then throws the errror. Any idea what the cause might be?

```
➜ npm run dev

> bootstrap5-webpack-boilerplate@1.0.1 dev
> webpack-dev-server --open --config webpack.config.js --mode development

<i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:9090/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.1.2:9090/
<i> [webpack-dev-server] On Your Network (IPv6): http://[fe80::1]:9090/
<i> [webpack-dev-server] Content not from webpack is served from '/Users/dokoissho/GitHub/bootstrap/bootstrap5-webpack/public' directory
<i> [webpack-dev-middleware] wait until bundle finished: /
/Users/dokoissho/GitHub/bootstrap/bootstrap5-webpack/node_modules/chokidar/lib/fsevents-handler.js:93
  const stop = fsevents.watch(path, callback);
                        ^

TypeError: fsevents.watch is not a function
    at createFSEventsInstance (/Users/dokoissho/GitHub/bootstrap/bootstrap5-webpack/node_modules/chokidar/lib/fsevents-handler.js:93:25)
    at setFSEventsListener (/Users/dokoissho/GitHub/bootstrap/bootstrap5-webpack/node_modules/chokidar/lib/fsevents-handler.js:149:16)
    at FsEventsHandler._watchWithFsEvents (/Users/dokoissho/GitHub/bootstrap/bootstrap5-webpack/node_modules/chokidar/lib/fsevents-handler.js:351:18)
    at FsEventsHandler.initWatch (/Users/dokoissho/GitHub/bootstrap/bootstrap5-webpack/node_modules/chokidar/lib/fsevents-handler.js:427:23)
    at FsEventsHandler._addToFsEvents (/Users/dokoissho/GitHub/bootstrap/bootstrap5-webpack/node_modules/chokidar/lib/fsevents-handler.js:516:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v20.0.0
```

**Comment by noreading** [comment]
I checked Node 20.6.1 on Windows with WSL and could not reproduce the error with the current version [v2.2.1](https://github.com/noreading/bootstrap5-webpack-boilerplate/releases/tag/v2.2.1). Please update to the latest version and let meknow your operating system, etc. if it still fails.
